---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend-targetgroup
  namespace: localhelp
spec:
  serviceRef:
    name: frontend
    port: 80

  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:837206354502:targetgroup/localhelp-dev-frontend/7a36b355cff8fb91

  targetType: ip