apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/ebs-static
    type: DirectoryOrCreate



---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: ebs-static

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
   app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: my-storage
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: ebs-static

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80

