apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0aef513372b8ed19c


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: efs-static


---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx

spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: my-storage
      mountPath: /usr/share/nginx/html

  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: efs-static

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb 
spec:
 type: LoadBalancer
 selector:
  app: nginx
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80