apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  tolerarations:
  - key: "workload"
    operator: "Equal"
    value: "devops"
    effect: "NoSchedule"